services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    InspiredMinds\ContaoUnifiedEventAliases\:
        resource: ../src/
        exclude: ../src/{ContaoManager,DependencyInjection,ContaoUnifiedEventAliasesBundle.php}
